spring:
  application:
    name: SpringJPAProject
    version: 2.0
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.100.100:1521/nwi
    username: nwsusa_india
    password: nwsusa_india
